-- =============================================================================
-- V1 — BASELINE DO CUIDADO (serviço Java)
-- =============================================================================
-- As OITO tabelas de que este serviço é dono, com chave primária, restrições de
-- domínio, as FKs INTERNAS ao cuidado e os índices.
--
-- Cinco vêm do cuidado desde sempre (T_PB_USUARIO, T_PB_PROTOCOLO,
-- T_PB_EVENTO_PROTOCOLO, T_PB_PLANO_CUIDADO_ANIMAL, T_PB_EVENTO_PLANO) e três
-- mudaram de dono em 08/09 — o cluster do check-in (T_PB_CHECKIN_TRATAMENTO,
-- T_PB_CHECKIN_EXTRACAO, T_PB_CHECKIN_RESULTADO), pelos aditamentos aos ADRs
-- s3-09 e s3-14: interpretar e registrar o check-in é cuidado, não registro.
-- As entidades JPA das três nascem no PR-J6; a tabela nasce aqui, e isso não
-- quebra o `validate` porque a validação só confere o que está mapeado.
--
-- POR QUE NÃO HÁ NENHUMA FOREIGN KEY PARA TABELA DO .NET (ADR s3-23)
--   Dez chaves saem daqui e apontam para as onze tabelas do registro, que quem
--   cria é a migration do Entity Framework, no MESMO schema Oracle. Se elas
--   estivessem neste arquivo, este baseline passaria a exigir que o .NET tivesse
--   migrado antes — a ordem de subida viraria dependência dura e o deploy de uma
--   aplicação só quebraria.
--   As dez estão no V2, que é o único passo ordenado e é o último de qualquer
--   jeito. Enquanto só o V1 e o EF tiverem rodado, a integridade entre serviços
--   fica na aplicação.
--
-- CONVENÇÕES (ADR s3-21 e cabeçalho do 01_ddl.sql)
--   Id é coluna IDENTITY — `GENERATED BY DEFAULT ON NULL AS IDENTITY`. Nenhuma
--   sequence nomeada: as entidades usam GenerationType.IDENTITY.
--   Ids do cuidado em NUMBER(19), porque as entidades usam `Long`. Vale também
--   para as três tabelas de check-in, que no 01_ddl.sql já estão em NUMBER(19)
--   desde que mudaram de lado.
--   As colunas que apontam para o registro também são NUMBER(19), contra
--   NUMBER(10) do destino: é a assimetria deliberada do 01_ddl.sql — cada lado
--   declara o que o próprio ORM gera. Oracle aceita a FK, a precisão não entra.
--
-- Fonte: `database/src/01_ddl.sql`, seção "CUIDADO · JAVA — 8 tabelas".
-- =============================================================================


-- -----------------------------------------------------------------------------
-- T_PB_USUARIO — login único para os dois perfis. O Java emite o JWT; o .NET
-- valida o mesmo token (ADRs s3-02 e s3-06).
--
-- Exatamente um dos dois ids de vínculo é preenchido, conforme o perfil.
-- Sem AT_UPDATED_AT: a entidade não tem o campo.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_USUARIO (
    ID_USUARIO       NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    DS_LOGIN         VARCHAR2(120)  NOT NULL,
    DS_SENHA_HASH    VARCHAR2(100)  NOT NULL,
    TP_PERFIL        VARCHAR2(20)   NOT NULL,
    ID_VETERINARIO   NUMBER(19),
    ID_RESPONSAVEL   NUMBER(19),
    AT_ATIVO         NUMBER(1)      DEFAULT 1 NOT NULL,
    CA_CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_T_PB_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UK_USUARIO_LOGIN UNIQUE (DS_LOGIN),
    CONSTRAINT CK_USUARIO_PERFIL CHECK (TP_PERFIL IN ('VET','TUTOR')),
    CONSTRAINT CK_USUARIO_ATIVO CHECK (AT_ATIVO IN (0,1)),
    -- o vínculo tem que casar com o perfil
    CONSTRAINT CK_USUARIO_VINCULO CHECK (
        (TP_PERFIL = 'VET'   AND ID_VETERINARIO IS NOT NULL AND ID_RESPONSAVEL IS NULL)
     OR (TP_PERFIL = 'TUTOR' AND ID_RESPONSAVEL IS NOT NULL AND ID_VETERINARIO IS NULL))
);

-- -----------------------------------------------------------------------------
-- T_PB_PROTOCOLO — a política da clínica: o que todo pet daquele perfil recebe.
-- Os campos de perfil nulos significam "não filtra por isso".
-- Sem AT_UPDATED_AT: a entidade não tem o campo.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_PROTOCOLO (
    ID_PROTOCOLO         NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NM_NOME              VARCHAR2(255)  NOT NULL,
    TP_CATEGORIA         VARCHAR2(50)   NOT NULL,
    ES_ESPECIE           VARCHAR2(50)   NOT NULL,
    PT_PORTE             VARCHAR2(50),
    SX_SEXO              VARCHAR2(50),
    CT_CASTRADO          NUMBER(1),
    AT_ATIVO             NUMBER(1)      DEFAULT 1 NOT NULL,
    NR_IDADE_MIN_MESES   NUMBER(5),
    NR_IDADE_MAX_MESES   NUMBER(5),
    DS_DESCRICAO         VARCHAR2(2000),
    CA_CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_T_PB_PROTOCOLO PRIMARY KEY (ID_PROTOCOLO),
    CONSTRAINT CK_PROTOCOLO_CATEGORIA CHECK (TP_CATEGORIA IN
        ('PREVENTIVO','POS_CIRURGICO')),
    CONSTRAINT CK_PROTOCOLO_ESPECIE CHECK (ES_ESPECIE IN
        ('CACHORRO','GATO','PASSARO','COELHO','HAMSTER','OUTRO')),
    CONSTRAINT CK_PROTOCOLO_PORTE CHECK (PT_PORTE IN
        ('MINI','PEQUENO','MEDIO','GRANDE','GIGANTE')),
    CONSTRAINT CK_PROTOCOLO_SEXO CHECK (SX_SEXO IN ('MACHO','FEMEA')),
    CONSTRAINT CK_PROTOCOLO_CASTRADO CHECK (CT_CASTRADO IN (0,1)),
    CONSTRAINT CK_PROTOCOLO_ATIVO CHECK (AT_ATIVO IN (0,1)),
    -- faixa de idade invertida nunca casaria com pet nenhum
    CONSTRAINT CK_PROTOCOLO_IDADE CHECK (
        NR_IDADE_MIN_MESES IS NULL OR NR_IDADE_MAX_MESES IS NULL
     OR NR_IDADE_MIN_MESES <= NR_IDADE_MAX_MESES)
);

-- -----------------------------------------------------------------------------
-- T_PB_EVENTO_PROTOCOLO — o molde do item, com agendamento unificado.
--
-- NR_OFFSET + TP_UNIDADE_OFFSET + TP_ANCORA dizem QUANDO a primeira ocorrência
-- cai. NR_INTERVALO nulo = ocorrência única.
--
-- NR_REPETICOES é OBRIGATÓRIO: item "para sempre" vira número explícito. Nulo
-- significando "enquanto o plano estiver ativo" gerava laço infinito, porque o
-- plano não tem fim.
-- Sem CA_CREATED_AT nem AT_UPDATED_AT: a entidade não tem os campos.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_EVENTO_PROTOCOLO (
    ID_EVENTO_PROTOCOLO    NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_PROTOCOLO           NUMBER(19)     NOT NULL,
    TP_TIPO                VARCHAR2(50)   NOT NULL,
    NM_NOME                VARCHAR2(255)  NOT NULL,
    NR_OFFSET              NUMBER(4)      NOT NULL,
    TP_UNIDADE_OFFSET      VARCHAR2(20)   NOT NULL,
    TP_ANCORA              VARCHAR2(20)   NOT NULL,
    NR_INTERVALO           NUMBER(4),
    TP_UNIDADE_INTERVALO   VARCHAR2(20),
    NR_REPETICOES          NUMBER(3)      NOT NULL,
    DS_DESCRICAO           VARCHAR2(2000),
    CONSTRAINT PK_T_PB_EVENTO_PROTOCOLO PRIMARY KEY (ID_EVENTO_PROTOCOLO),
    CONSTRAINT CK_EVPROT_TIPO CHECK (TP_TIPO IN
        ('VACINACAO','VERMIFUGACAO','EXAME','RETORNO','CIRURGIA','MEDICACAO','HIGIENE')),
    CONSTRAINT CK_EVPROT_UNID_OFFSET CHECK (TP_UNIDADE_OFFSET IN
        ('DIAS','SEMANAS','MESES')),
    CONSTRAINT CK_EVPROT_ANCORA CHECK (TP_ANCORA IN
        ('INSTANCIACAO','NASCIMENTO','DATA_CIRURGIA')),
    CONSTRAINT CK_EVPROT_UNID_INTERV CHECK (TP_UNIDADE_INTERVALO IN
        ('DIAS','SEMANAS','MESES')),
    -- intervalo sem unidade não sabe se repete em dias ou em meses;
    -- unidade sem intervalo não repete nada
    CONSTRAINT CK_EVPROT_RECORRENCIA CHECK (
        (NR_INTERVALO IS NULL     AND TP_UNIDADE_INTERVALO IS NULL)
     OR (NR_INTERVALO IS NOT NULL AND TP_UNIDADE_INTERVALO IS NOT NULL)),
    CONSTRAINT CK_EVPROT_REPETICOES CHECK (NR_REPETICOES >= 1)
);

-- -----------------------------------------------------------------------------
-- T_PB_PLANO_CUIDADO_ANIMAL — o plano vivo do pet.
-- ID_ANIMAL e ID_CONSULTA atravessam para o .NET — a FK deles está no V2.
-- ID_PROTOCOLO é nulável: plano só de prescrição não tem protocolo.
-- Sem cancelamento: não é ação da Sprint 3.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_PLANO_CUIDADO_ANIMAL (
    ID_PLANO_CUIDADO_ANIMAL   NUMBER(19)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_ANIMAL                 NUMBER(19)    NOT NULL,
    ID_CONSULTA               NUMBER(19),
    ID_PROTOCOLO              NUMBER(19),
    ST_STATUS                 VARCHAR2(50)  NOT NULL,
    CA_CREATED_AT             TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT             TIMESTAMP,
    CONSTRAINT PK_T_PB_PLANO PRIMARY KEY (ID_PLANO_CUIDADO_ANIMAL),
    CONSTRAINT CK_PLANO_STATUS CHECK (ST_STATUS IN ('ATIVO','CONCLUIDO','CANCELADO'))
);

-- -----------------------------------------------------------------------------
-- T_PB_EVENTO_PLANO — o item do checklist: uma linha por dose ou aplicação.
-- Um tratamento de 10 dias são 10 linhas com o mesmo ID_PRESCRICAO.
--
-- TP_ORIGEM é o que decide o rótulo da tela: PRESCRICAO é "você faz em casa",
-- PROTOCOLO é "na clínica". Não existe coluna de executor — é derivado.
--
-- ID_EVENTO_PROTOCOLO é nulável: item vindo de prescrição não tem molde.
-- ID_PRESCRICAO e ID_PROCEDIMENTO atravessam para o .NET — FKs no V2.
-- Sem CA_CREATED_AT: a entidade não tem o campo.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_EVENTO_PLANO (
    ID_EVENTO_PLANO           NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_PLANO_CUIDADO_ANIMAL   NUMBER(19)     NOT NULL,
    ID_EVENTO_PROTOCOLO       NUMBER(19),
    TP_ORIGEM                 VARCHAR2(20)   NOT NULL,
    ID_PRESCRICAO             NUMBER(19),
    TP_TIPO                   VARCHAR2(50)   NOT NULL,
    NM_NOME                   VARCHAR2(255)  NOT NULL,
    DT_DATA_ALVO              DATE           NOT NULL,
    ST_STATUS                 VARCHAR2(50)   NOT NULL,
    OB_OBSERVACAO             VARCHAR2(2000),
    ID_PROCEDIMENTO           NUMBER(19),
    DT_EXECUTADO_EM           TIMESTAMP,
    AT_UPDATED_AT             TIMESTAMP,
    CONSTRAINT PK_T_PB_EVENTO_PLANO PRIMARY KEY (ID_EVENTO_PLANO),
    CONSTRAINT CK_EVPLANO_ORIGEM CHECK (TP_ORIGEM IN ('PROTOCOLO','PRESCRICAO')),
    CONSTRAINT CK_EVPLANO_TIPO CHECK (TP_TIPO IN
        ('VACINACAO','VERMIFUGACAO','EXAME','RETORNO','CIRURGIA','MEDICACAO','HIGIENE')),
    CONSTRAINT CK_EVPLANO_STATUS CHECK (ST_STATUS IN
        ('PENDENTE','REALIZADO','CANCELADO','ATRASADO')),
    -- item de prescrição precisa dizer de qual;
    -- item de protocolo precisa do molde que o gerou
    CONSTRAINT CK_EVPLANO_ORIGEM_COER CHECK (
        (TP_ORIGEM = 'PRESCRICAO' AND ID_PRESCRICAO IS NOT NULL)
     OR (TP_ORIGEM = 'PROTOCOLO'  AND ID_EVENTO_PROTOCOLO IS NOT NULL))
);

-- -----------------------------------------------------------------------------
-- T_PB_CHECKIN_TRATAMENTO — o cabeçalho: um relato por pet e por momento.
-- Cobre todos os remédios de uma vez: "as fezes tavam moles" vale para toda
-- prescrição avaliada naquele check-in.
--
-- Guarda a TRANSCRIÇÃO, não o áudio (ADR s3-18) — não há AU_AUDIO_URL.
-- DS_TIC_UTILIZADA atende o Art. 13 §5º da resolução do CFMV.
-- Sem coluna de status: a linha só nasce quando o tutor confirma.
-- ID_ANIMAL atravessa para o .NET — a FK está no V2.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_CHECKIN_TRATAMENTO (
    ID_CHECKIN_TRATAMENTO   NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_ANIMAL               NUMBER(19)     NOT NULL,
    DH_REGISTRADO_EM        TIMESTAMP(7)   NOT NULL,
    TX_NARRATIVA            CLOB           NOT NULL,
    TX_OBSERVACOES_GERAIS   CLOB,
    DS_TIC_UTILIZADA        VARCHAR2(120),
    CA_CREATED_AT           TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT           TIMESTAMP(7),
    CONSTRAINT PK_T_PB_CHECKIN_TRAT PRIMARY KEY (ID_CHECKIN_TRATAMENTO)
);

-- -----------------------------------------------------------------------------
-- T_PB_CHECKIN_EXTRACAO — o que a IA extraiu do relato: uma linha por condição
-- observada. Aponta para o CATÁLOGO, não para a regra — o tutor pode relatar
-- condição que nenhuma regra cobre ("apetite reduzido"), e isso fica registrado.
-- Imutável: AT_UPDATED_AT fica nulo por contrato.
-- ID_CONDICAO_CLINICA atravessa para o .NET — a FK está no V2.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_CHECKIN_EXTRACAO (
    ID_CHECKIN_EXTRACAO     NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_CHECKIN_TRATAMENTO   NUMBER(19)     NOT NULL,
    ID_CONDICAO_CLINICA     NUMBER(19)     NOT NULL,
    CD_CODIGO_CONGELADO     VARCHAR2(60)   NOT NULL,
    BL_VALOR_BOOLEANO       NUMBER(1),
    NR_VALOR_NUMERICO       NUMBER(10,3),
    NR_CONFIANCA            NUMBER(5,4)    NOT NULL,
    CA_CREATED_AT           TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT           TIMESTAMP(7),
    CONSTRAINT PK_T_PB_CHECKIN_EXTRACAO PRIMARY KEY (ID_CHECKIN_EXTRACAO),
    CONSTRAINT CK_EXTRACAO_BOOLEANO CHECK (BL_VALOR_BOOLEANO IN (0,1)),
    -- confiança da IA é probabilidade, não escala livre
    CONSTRAINT CK_EXTRACAO_CONFIANCA CHECK (NR_CONFIANCA BETWEEN 0 AND 1),
    -- exatamente um dos dois valores é preenchido, conforme o TP_VALOR da condição
    CONSTRAINT CK_EXTRACAO_UM_VALOR CHECK (
        (BL_VALOR_BOOLEANO IS NOT NULL AND NR_VALOR_NUMERICO IS NULL)
     OR (BL_VALOR_BOOLEANO IS NULL AND NR_VALOR_NUMERICO IS NOT NULL))
);

-- -----------------------------------------------------------------------------
-- T_PB_CHECKIN_RESULTADO — a dose do dia: uma linha por prescrição avaliada
-- naquele check-in. Um relato, N doses.
--
-- A UNICIDADE (ID_PRESCRICAO, DT_REFERENCIA) É A TRAVA DA ADESÃO. Sem ela o
-- mesmo dia de tratamento entra duas vezes e "dia 4 de 10" passa a contar 11.
--
-- NR_DOSE_APLICADA é NULO quando TP_DESFECHO é SEM_DOSE ou ACIONAR_CLINICA.
-- ID_PRESCRICAO e ID_REGRA_APLICADA atravessam para o .NET — FKs no V2.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_CHECKIN_RESULTADO (
    ID_CHECKIN_RESULTADO    NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_CHECKIN_TRATAMENTO   NUMBER(19)     NOT NULL,
    ID_PRESCRICAO           NUMBER(19)     NOT NULL,
    DT_REFERENCIA           DATE           NOT NULL,
    TP_DESFECHO             VARCHAR2(30)   NOT NULL,
    NR_DOSE_APLICADA        NUMBER(8,3),
    ID_REGRA_APLICADA       NUMBER(19),
    CA_CREATED_AT           TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT           TIMESTAMP(7),
    CONSTRAINT PK_T_PB_CHECKIN_RESULTADO PRIMARY KEY (ID_CHECKIN_RESULTADO),
    CONSTRAINT UK_RESULTADO_PRESC_DATA UNIQUE (ID_PRESCRICAO, DT_REFERENCIA),
    CONSTRAINT CK_RESULTADO_DESFECHO CHECK (TP_DESFECHO IN
        ('DOSE_CALCULADA','ACIONAR_CLINICA','SEM_DOSE')),
    -- só o desfecho DOSE_CALCULADA carrega dose
    CONSTRAINT CK_RESULTADO_DOSE CHECK (
        (TP_DESFECHO = 'DOSE_CALCULADA' AND NR_DOSE_APLICADA IS NOT NULL)
     OR (TP_DESFECHO <> 'DOSE_CALCULADA' AND NR_DOSE_APLICADA IS NULL))
);


-- =============================================================================
-- CHAVES ESTRANGEIRAS — SÓ AS INTERNAS AO CUIDADO
-- As dez que apontam para o registro estão no V2, e nenhuma delas aqui.
-- =============================================================================

ALTER TABLE T_PB_EVENTO_PROTOCOLO ADD CONSTRAINT FK_EVPROT_PROTOCOLO
    FOREIGN KEY (ID_PROTOCOLO) REFERENCES T_PB_PROTOCOLO (ID_PROTOCOLO);

ALTER TABLE T_PB_PLANO_CUIDADO_ANIMAL ADD CONSTRAINT FK_PLANO_PROTOCOLO
    FOREIGN KEY (ID_PROTOCOLO) REFERENCES T_PB_PROTOCOLO (ID_PROTOCOLO);

ALTER TABLE T_PB_EVENTO_PLANO ADD CONSTRAINT FK_EVPLANO_PLANO
    FOREIGN KEY (ID_PLANO_CUIDADO_ANIMAL) REFERENCES T_PB_PLANO_CUIDADO_ANIMAL (ID_PLANO_CUIDADO_ANIMAL) ON DELETE CASCADE;
ALTER TABLE T_PB_EVENTO_PLANO ADD CONSTRAINT FK_EVPLANO_EVPROT
    FOREIGN KEY (ID_EVENTO_PROTOCOLO) REFERENCES T_PB_EVENTO_PROTOCOLO (ID_EVENTO_PROTOCOLO);

-- Cascade só do cabeçalho do check-in para as filhas — apagar o relato apaga o
-- que foi extraído e decidido a partir dele.
ALTER TABLE T_PB_CHECKIN_EXTRACAO ADD CONSTRAINT FK_CKEXTR_CHECKIN
    FOREIGN KEY (ID_CHECKIN_TRATAMENTO) REFERENCES T_PB_CHECKIN_TRATAMENTO (ID_CHECKIN_TRATAMENTO) ON DELETE CASCADE;

ALTER TABLE T_PB_CHECKIN_RESULTADO ADD CONSTRAINT FK_CKRES_CHECKIN
    FOREIGN KEY (ID_CHECKIN_TRATAMENTO) REFERENCES T_PB_CHECKIN_TRATAMENTO (ID_CHECKIN_TRATAMENTO) ON DELETE CASCADE;


-- =============================================================================
-- ÍNDICES
-- Oracle já indexa PK e UNIQUE. Aqui ficam só os de FK e de consulta que o banco
-- não cria sozinho — e só os das oito tabelas do cuidado.
-- =============================================================================

-- "os check-ins deste pet, do mais recente para o mais antigo" — não único:
-- o tutor pode relatar duas vezes no mesmo dia
CREATE INDEX IX_CKTRAT_ANIMAL_DATA ON T_PB_CHECKIN_TRATAMENTO (ID_ANIMAL, DH_REGISTRADO_EM);

-- o checklist do tutor filtra por data-alvo dentro do plano
CREATE INDEX IX_EVPLANO_PLANO_DATA ON T_PB_EVENTO_PLANO (ID_PLANO_CUIDADO_ANIMAL, DT_DATA_ALVO);

-- a reconciliação do lado Java procura o item pela prescrição
CREATE INDEX IX_EVPLANO_PRESCRICAO ON T_PB_EVENTO_PLANO (ID_PRESCRICAO);
