-- =============================================================================
-- V1 — BASELINE DO CUIDADO (serviço Java)
-- =============================================================================
-- As SETE tabelas de que este serviço é dono, com chave primária, restrições de
-- domínio, as FKs INTERNAS ao cuidado e os índices.
--
-- REESCRITO NO PR-J8 (ADR s3-24, 09/09), e não acrescentado num V4. Legítimo por
-- um motivo só: este baseline NUNCA rodou contra o Oracle. Se tiver rodado antes
-- do merge, este arquivo volta ao que era e a mudança vira V4.
--
-- O QUE MUDOU EM RELAÇÃO À VERSÃO ANTERIOR
--   · T_PB_CHECKIN_RESULTADO deixou de existir. As quatro colunas de decisão
--     (ID_CHECKIN, TP_DESFECHO, NR_DOSE_APLICADA, ID_REGRA_APLICADA) moram dentro
--     de T_PB_ITEM_PLANO_CUIDADO, ao lado de ID_PROCEDIMENTO e DT_EXECUTADO_EM,
--     que já estavam lá: são as duas metades do mesmo padrão de baixa.
--   · Sete tabelas renomeadas e dez colunas de enum sufixadas (s3-24 §7b).
--   · T_PB_PROTOCOLO perdeu porte, sexo, castração e faixa de idade — o matching
--     por perfil do pet era herança do bot. Sobrou ES_ESPECIE.
--   · TP_DATA_BASE (ex-TP_ANCORA) perdeu INSTANCIACAO e ganhou ULTIMA_REALIZACAO.
--   · T_PB_PLANO_CUIDADO ganhou TP_CATEGORIA_PLANO, própria e não herdada do
--     protocolo — é o que permite plano de tratamento sem protocolo.
--
-- AS ENTIDADES JPA DE T_PB_CHECKIN E T_PB_CONDICAO_OBSERVADA NASCEM NO PR-J6.
-- A tabela nasce aqui, e isso não quebra o `validate`: ele só confere o que está
-- mapeado.
--
-- POR QUE NÃO HÁ NENHUMA FOREIGN KEY PARA TABELA DO .NET (ADR s3-23)
--   Nove chaves saem daqui e apontam para as onze tabelas do registro, que quem
--   cria é a migration do Entity Framework, no MESMO schema Oracle. Se elas
--   estivessem neste arquivo, este baseline passaria a exigir que o .NET tivesse
--   migrado antes — a ordem de subida viraria dependência dura e o deploy de uma
--   aplicação só quebraria. Elas vivem no V2.
--
-- FONTE: database/src/01_ddl.sql, commit a73a473. Este arquivo é derivado; em
-- caso de divergência, o DDL da disciplina de banco é o canônico.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- T_PB_CHECKIN — o cabeçalho: um relato por pet e por momento
-- (decisão D). Cobre todos os remédios de uma vez: "as fezes tavam moles" vale
-- para toda prescrição avaliada naquele check-in.
--
-- Guarda a TRANSCRIÇÃO, não o áudio (ADR s3-18) — não há AU_AUDIO_URL.
-- DS_TIC_UTILIZADA atende o Art. 13 §5º da resolução do CFMV.
-- Sem coluna de status: a linha só nasce quando o tutor confirma.
--
-- DOIS MODOS DE RELATO (ADR s3-24, §6). ID_ITEM_PLANO_CUIDADO nulo é o relato
-- GERAL do dia — "como o Thor passou?" — e é o caminho principal. Preenchido, é
-- relato sobre um item específico.
--
-- A unicidade (ID_ANIMAL, DT_REFERENCIA, ID_ITEM_PLANO_CUIDADO) dá exatamente
-- isso sem trigger e sem regra na aplicação: **o Oracle conta chave
-- parcialmente nula para unicidade**, então o nulo permite um único relato geral
-- por pet por dia, e cada item aceita o seu. É a mesma propriedade que, mal
-- usada, quebraria o índice do item (ver UX_ITEM_PRESC_DATA adiante) — aqui ela
-- trabalha a favor.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_CHECKIN (
    ID_CHECKIN              NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_ANIMAL               NUMBER(19)     NOT NULL,
    ID_ITEM_PLANO_CUIDADO   NUMBER(19),
    DT_REFERENCIA           DATE           NOT NULL,
    DH_REGISTRADO_EM        TIMESTAMP(7)   NOT NULL,
    TX_NARRATIVA            CLOB           NOT NULL,
    TX_OBSERVACOES_GERAIS   CLOB,
    DS_TIC_UTILIZADA        VARCHAR2(120),
    CA_CREATED_AT           TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT           TIMESTAMP(7),
    CONSTRAINT PK_T_PB_CHECKIN PRIMARY KEY (ID_CHECKIN),
    CONSTRAINT UK_CHECKIN_ANIMAL_DIA UNIQUE (ID_ANIMAL, DT_REFERENCIA, ID_ITEM_PLANO_CUIDADO)
);

-- -----------------------------------------------------------------------------
-- T_PB_CONDICAO_OBSERVADA — o que a IA extraiu do relato: uma linha por condição
-- observada. Aponta para o CATÁLOGO, não para a regra — o tutor pode relatar
-- condição que nenhuma regra cobre ("apetite reduzido"), e isso fica registrado.
-- Imutável: AT_UPDATED_AT fica nulo por contrato.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_CONDICAO_OBSERVADA (
    ID_CONDICAO_OBSERVADA     NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_CHECKIN   NUMBER(19)     NOT NULL,
    ID_CONDICAO_CLINICA     NUMBER(19)     NOT NULL,
    CD_CODIGO_CONGELADO     VARCHAR2(60)   NOT NULL,
    BL_VALOR_BOOLEANO       NUMBER(1),
    NR_VALOR_NUMERICO       NUMBER(10,3),
    NR_CONFIANCA            NUMBER(5,4)    NOT NULL,
    CA_CREATED_AT           TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT           TIMESTAMP(7),
    CONSTRAINT PK_T_PB_CONDICAO_OBSERVADA PRIMARY KEY (ID_CONDICAO_OBSERVADA),
    CONSTRAINT CK_COBS_BOOLEANO CHECK (BL_VALOR_BOOLEANO IN (0,1)),
    -- [proposta desta sessão] confiança da IA é probabilidade, não escala livre.
    CONSTRAINT CK_COBS_CONFIANCA CHECK (NR_CONFIANCA BETWEEN 0 AND 1),
    -- [proposta desta sessão] exatamente um dos dois valores é preenchido,
    -- conforme o TP_DADO da condição.
    CONSTRAINT CK_COBS_UM_VALOR CHECK (
        (BL_VALOR_BOOLEANO IS NOT NULL AND NR_VALOR_NUMERICO IS NULL)
     OR (BL_VALOR_BOOLEANO IS NULL AND NR_VALOR_NUMERICO IS NOT NULL))
);

-- -----------------------------------------------------------------------------
-- T_PB_USUARIO — login único para os dois perfis. O Java emite o JWT; o .NET
-- valida o mesmo token (ADRs s3-02 e s3-06).
--
-- Exatamente um dos dois ids de vínculo é preenchido, conforme o perfil.
-- Sem AT_UPDATED_AT: a entidade não tem o campo.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_USUARIO (
    ID_USUARIO       NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    DS_LOGIN         VARCHAR2(120)  NOT NULL,
    DS_SENHA_HASH    VARCHAR2(100)  NOT NULL,
    TP_PERFIL        VARCHAR2(20)   NOT NULL,
    ID_VETERINARIO   NUMBER(19),
    ID_RESPONSAVEL   NUMBER(19),
    AT_ATIVO         NUMBER(1)      DEFAULT 1 NOT NULL,
    CA_CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_T_PB_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UK_USUARIO_LOGIN UNIQUE (DS_LOGIN),
    CONSTRAINT CK_USUARIO_PERFIL CHECK (TP_PERFIL IN ('VET','TUTOR')),
    CONSTRAINT CK_USUARIO_ATIVO CHECK (AT_ATIVO IN (0,1)),
    -- [proposta desta sessão] o vínculo tem que casar com o perfil.
    CONSTRAINT CK_USUARIO_VINCULO CHECK (
        (TP_PERFIL = 'VET'   AND ID_VETERINARIO IS NOT NULL AND ID_RESPONSAVEL IS NULL)
     OR (TP_PERFIL = 'TUTOR' AND ID_RESPONSAVEL IS NOT NULL AND ID_VETERINARIO IS NULL))
);

-- -----------------------------------------------------------------------------
-- T_PB_PROTOCOLO — a política da clínica: o que todo pet daquele perfil recebe.
-- Os campos de perfil nulos significam "não filtra por isso".
-- Sem AT_UPDATED_AT: a entidade não tem o campo.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_PROTOCOLO (
    ID_PROTOCOLO         NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NM_NOME              VARCHAR2(255)  NOT NULL,
    TP_CATEGORIA_PROTOCOLO         VARCHAR2(50)   NOT NULL,
    ES_ESPECIE           VARCHAR2(50)   NOT NULL,
    AT_ATIVO             NUMBER(1)      DEFAULT 1 NOT NULL,
    DS_DESCRICAO         VARCHAR2(2000),
    CA_CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_T_PB_PROTOCOLO PRIMARY KEY (ID_PROTOCOLO),
    CONSTRAINT CK_PROTOCOLO_CATEGORIA CHECK (TP_CATEGORIA_PROTOCOLO IN
        ('PREVENTIVO','POS_CIRURGICO')),
    CONSTRAINT CK_PROTOCOLO_ESPECIE CHECK (ES_ESPECIE IN
        ('CACHORRO','GATO','PASSARO','COELHO','HAMSTER','OUTRO')),
    CONSTRAINT CK_PROTOCOLO_ATIVO CHECK (AT_ATIVO IN (0,1))
);

-- -----------------------------------------------------------------------------
-- T_PB_REGRA_PROTOCOLO — o molde do item, com agendamento unificado.
--
-- NR_OFFSET + TP_UNIDADE_OFFSET + TP_DATA_BASE dizem QUANDO a primeira ocorrência
-- cai. NR_INTERVALO nulo = ocorrência única.
--
-- NR_REPETICOES é OBRIGATÓRIO: item "para sempre" vira número explícito. Nulo
-- significando "enquanto o plano estiver ativo" gerava laço infinito, porque o
-- plano não tem fim (achado nº 7 do code review).
-- Sem CA_CREATED_AT nem AT_UPDATED_AT: a entidade não tem os campos.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_REGRA_PROTOCOLO (
    ID_REGRA_PROTOCOLO    NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_PROTOCOLO           NUMBER(19)     NOT NULL,
    TP_TIPO_CUIDADO                VARCHAR2(50)   NOT NULL,
    NM_NOME                VARCHAR2(255)  NOT NULL,
    NR_OFFSET              NUMBER(4)      NOT NULL,
    TP_UNIDADE_OFFSET      VARCHAR2(20)   NOT NULL,
    TP_DATA_BASE              VARCHAR2(20)   NOT NULL,
    NR_INTERVALO           NUMBER(4),
    TP_UNIDADE_INTERVALO   VARCHAR2(20),
    NR_REPETICOES          NUMBER(3)      NOT NULL,
    DS_DESCRICAO           VARCHAR2(2000),
    CONSTRAINT PK_T_PB_REGRA_PROTOCOLO PRIMARY KEY (ID_REGRA_PROTOCOLO),
    CONSTRAINT CK_REGPROT_TIPO CHECK (TP_TIPO_CUIDADO IN
        ('VACINACAO','VERMIFUGACAO','EXAME','RETORNO','CIRURGIA','MEDICACAO','HIGIENE')),
    CONSTRAINT CK_REGPROT_UNID_OFFSET CHECK (TP_UNIDADE_OFFSET IN
        ('DIAS','SEMANAS','MESES')),
    CONSTRAINT CK_REGPROT_ANCORA CHECK (TP_DATA_BASE IN
        ('NASCIMENTO','DATA_CIRURGIA','ULTIMA_REALIZACAO')),
    CONSTRAINT CK_REGPROT_UNID_INTERV CHECK (TP_UNIDADE_INTERVALO IN
        ('DIAS','SEMANAS','MESES')),
    -- [proposta desta sessão] intervalo sem unidade não sabe se repete em dias
    -- ou em meses; unidade sem intervalo não repete nada.
    CONSTRAINT CK_REGPROT_RECORRENCIA CHECK (
        (NR_INTERVALO IS NULL     AND TP_UNIDADE_INTERVALO IS NULL)
     OR (NR_INTERVALO IS NOT NULL AND TP_UNIDADE_INTERVALO IS NOT NULL)),
    CONSTRAINT CK_REGPROT_REPETICOES CHECK (NR_REPETICOES >= 1)
);

-- -----------------------------------------------------------------------------
-- T_PB_PLANO_CUIDADO — o plano vivo do pet.
-- ID_ANIMAL e ID_CONSULTA atravessam para o .NET (decisão B).
-- ID_PROTOCOLO é nulável: plano de TRATAMENTO nasce de prescrição, sem molde.
-- Sem cancelamento: não é ação da Sprint 3 (decisão I).
--
-- TP_CATEGORIA_PLANO é própria do plano (ADR s3-24, §4), e não herdada do protocolo.
-- Antes, saber a categoria exigia join com T_PB_PROTOCOLO — e isso EXCLUÍA todo
-- plano com ID_PROTOCOLO nulo, que é justamente o de tratamento. A query de
-- idempotência do motor tinha esse furo.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_PLANO_CUIDADO (
    ID_PLANO_CUIDADO          NUMBER(19)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_ANIMAL                 NUMBER(19)    NOT NULL,
    ID_CONSULTA               NUMBER(19),
    ID_PROTOCOLO              NUMBER(19),
    TP_CATEGORIA_PLANO              VARCHAR2(20)  NOT NULL,
    ST_STATUS_PLANO                 VARCHAR2(50)  NOT NULL,
    CA_CREATED_AT             TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    AT_UPDATED_AT             TIMESTAMP,
    CONSTRAINT PK_T_PB_PLANO PRIMARY KEY (ID_PLANO_CUIDADO),
    CONSTRAINT CK_PLANO_STATUS CHECK (ST_STATUS_PLANO IN ('ATIVO','CONCLUIDO','CANCELADO')),
    CONSTRAINT CK_PLANO_CATEGORIA CHECK (TP_CATEGORIA_PLANO IN
        ('PREVENTIVO','POS_CIRURGICO','TRATAMENTO'))
);

-- -----------------------------------------------------------------------------
-- T_PB_ITEM_PLANO_CUIDADO — o item do checklist: uma linha por dose ou aplicação.
-- Um tratamento de 10 dias são 10 linhas com o mesmo ID_PRESCRICAO.
--
-- TP_ORIGEM é o que decide o rótulo da tela: PRESCRICAO é "você faz em casa",
-- PROTOCOLO é "na clínica". Não existe coluna de executor — é derivado.
--
-- ID_REGRA_PROTOCOLO é nulável: item vindo de prescrição não tem molde.
-- ID_PRESCRICAO e ID_PROCEDIMENTO atravessam para o .NET (decisão B).
-- Sem CA_CREATED_AT: a entidade não tem o campo.
--
-- A EXECUÇÃO MORA AQUI (ADR s3-24, §5). T_PB_CHECKIN_RESULTADO deixou de
-- existir. O item já carregava metade do padrão de baixa — ID_PROCEDIMENTO e
-- DT_EXECUTADO_EM, o "quem me baixou" do item da clínica. Recebe agora a outra
-- metade, para o item de casa: ID_CHECKIN, TP_DESFECHO, NR_DOSE_APLICADA e
-- ID_REGRA_APLICADA.
--
-- Some com isso uma duplicidade que ninguém queria: ST_STATUS_ITEM dizia *se* o item
-- foi feito, e TP_DESFECHO dizia *se e por quê*. Duas verdades, um fato.
--
-- O PREÇO, aceito na decisão: quatro colunas nulas em todo item de origem
-- PROTOCOLO. O item já tinha duas assim, então a forma não é nova.
-- -----------------------------------------------------------------------------
CREATE TABLE T_PB_ITEM_PLANO_CUIDADO (
    ID_ITEM_PLANO_CUIDADO           NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ID_PLANO_CUIDADO   NUMBER(19)     NOT NULL,
    ID_REGRA_PROTOCOLO       NUMBER(19),
    TP_ORIGEM                 VARCHAR2(20)   NOT NULL,
    ID_PRESCRICAO             NUMBER(19),
    TP_TIPO_CUIDADO                   VARCHAR2(50)   NOT NULL,
    NM_NOME                   VARCHAR2(255)  NOT NULL,
    DT_DATA_ALVO              DATE           NOT NULL,
    ST_STATUS_ITEM                 VARCHAR2(50)   NOT NULL,
    OB_OBSERVACAO             VARCHAR2(2000),
    ID_PROCEDIMENTO           NUMBER(19),
    DT_EXECUTADO_EM           TIMESTAMP,
    ID_CHECKIN                NUMBER(19),
    TP_DESFECHO               VARCHAR2(30),
    NR_DOSE_APLICADA          NUMBER(8,3),
    ID_REGRA_APLICADA         NUMBER(19),
    AT_UPDATED_AT             TIMESTAMP,
    CONSTRAINT PK_T_PB_ITEM_PLANO_CUIDADO PRIMARY KEY (ID_ITEM_PLANO_CUIDADO),
    CONSTRAINT CK_ITEM_ORIGEM CHECK (TP_ORIGEM IN ('PROTOCOLO','PRESCRICAO')),
    CONSTRAINT CK_ITEM_TIPO CHECK (TP_TIPO_CUIDADO IN
        ('VACINACAO','VERMIFUGACAO','EXAME','RETORNO','CIRURGIA','MEDICACAO','HIGIENE')),
    CONSTRAINT CK_ITEM_STATUS CHECK (ST_STATUS_ITEM IN
        ('PENDENTE','REALIZADO','CANCELADO','ATRASADO')),
    -- [proposta desta sessão] item de prescrição precisa dizer de qual;
    -- item de protocolo precisa do molde que o gerou.
    CONSTRAINT CK_ITEM_ORIGEM_COER CHECK (
        (TP_ORIGEM = 'PRESCRICAO' AND ID_PRESCRICAO IS NOT NULL)
     OR (TP_ORIGEM = 'PROTOCOLO'  AND ID_REGRA_PROTOCOLO IS NOT NULL)),
    CONSTRAINT CK_ITEM_DESFECHO CHECK (TP_DESFECHO IN
        ('DOSE_CALCULADA','ACIONAR_CLINICA','SEM_DOSE')),
    -- [proposta desta sessão, adotada no ADR s3-24] o CHECK da dose virou
    -- TERNÁRIO com a fusão. Antes era binário, porque toda linha da tabela morta
    -- tinha desfecho. Agora item de origem PROTOCOLO não tem nenhum — e sem o
    -- primeiro ramo, todo item de vacina seria recusado.
    CONSTRAINT CK_ITEM_DESFECHO_DOSE CHECK (
        (TP_DESFECHO IS NULL             AND NR_DOSE_APLICADA IS NULL)
     OR (TP_DESFECHO =  'DOSE_CALCULADA' AND NR_DOSE_APLICADA IS NOT NULL)
     OR (TP_DESFECHO <> 'DOSE_CALCULADA' AND NR_DOSE_APLICADA IS NULL))
);


-- =============================================================================
--


-- =============================================================================
-- FOREIGN KEYS INTERNAS AO CUIDADO
-- =============================================================================
ALTER TABLE T_PB_REGRA_PROTOCOLO ADD CONSTRAINT FK_REGPROT_PROTOCOLO
    FOREIGN KEY (ID_PROTOCOLO) REFERENCES T_PB_PROTOCOLO (ID_PROTOCOLO);

ALTER TABLE T_PB_PLANO_CUIDADO ADD CONSTRAINT FK_PLANO_PROTOCOLO
    FOREIGN KEY (ID_PROTOCOLO) REFERENCES T_PB_PROTOCOLO (ID_PROTOCOLO);

ALTER TABLE T_PB_ITEM_PLANO_CUIDADO ADD CONSTRAINT FK_ITEM_PLANO
    FOREIGN KEY (ID_PLANO_CUIDADO) REFERENCES T_PB_PLANO_CUIDADO (ID_PLANO_CUIDADO) ON DELETE CASCADE;
-- CICLO DELIBERADO, e por isso as duas colunas são nuláveis: o check-in aponta
-- para o item de que fala (relato por item), e o item aponta para o check-in que
-- o baixou. São relações diferentes entre as mesmas tabelas. O Oracle aceita,
-- porque nenhuma ponta é obrigatória — mas a CARGA precisa de ORDEM: primeiro
-- os relatos gerais, depois os itens, e só então o relato por item. Ver o
-- bloco 03.
ALTER TABLE T_PB_ITEM_PLANO_CUIDADO ADD CONSTRAINT FK_ITEM_CHECKIN
    FOREIGN KEY (ID_CHECKIN) REFERENCES T_PB_CHECKIN (ID_CHECKIN);
ALTER TABLE T_PB_CHECKIN ADD CONSTRAINT FK_CHECKIN_ITEM
    FOREIGN KEY (ID_ITEM_PLANO_CUIDADO) REFERENCES T_PB_ITEM_PLANO_CUIDADO (ID_ITEM_PLANO_CUIDADO);

ALTER TABLE T_PB_ITEM_PLANO_CUIDADO ADD CONSTRAINT FK_ITEM_REGPROT
    FOREIGN KEY (ID_REGRA_PROTOCOLO) REFERENCES T_PB_REGRA_PROTOCOLO (ID_REGRA_PROTOCOLO);

--


-- =============================================================================
-- ÍNDICES
-- Oracle já indexa PK e UNIQUE. Aqui ficam só os de FK e de consulta.
-- =============================================================================
CREATE INDEX IX_CHECKIN_ANIMAL_DATA ON T_PB_CHECKIN (ID_ANIMAL, DH_REGISTRADO_EM);
CREATE INDEX IX_ITEM_PLANO_DATA ON T_PB_ITEM_PLANO_CUIDADO (ID_PLANO_CUIDADO, DT_DATA_ALVO);
CREATE INDEX IX_ITEM_PRESCRICAO ON T_PB_ITEM_PLANO_CUIDADO (ID_PRESCRICAO);
CREATE INDEX IX_ITEM_DESFECHO ON T_PB_ITEM_PLANO_CUIDADO (TP_DESFECHO);

-- A TRAVA DA ADESÃO, herdada de UK_RESULTADO_PRESC_DATA quando a execução virou
-- coluna do item. Índice FUNCIONAL, e não UNIQUE composta, de propósito: no
-- Oracle uma chave PARCIALMENTE nula conta para a unicidade, e todo item de
-- origem PROTOCOLO tem ID_PRESCRICAO nulo — duas vacinas na mesma data
-- colidiriam. Com o CASE, chave inteiramente nula repete à vontade.
CREATE UNIQUE INDEX UX_ITEM_PRESC_DATA ON T_PB_ITEM_PLANO_CUIDADO
    (ID_PRESCRICAO, CASE WHEN ID_PRESCRICAO IS NOT NULL THEN DT_DATA_ALVO END);
