-- =============================================================================
-- V2 — AS NOVE FOREIGN KEYS QUE CRUZAM SERVIÇO (ADR s3-23)
-- =============================================================================
-- Separadas do baseline porque exigem que as tabelas do .NET já existam. O V1
-- sobe sozinho; este exige o registro migrado.
--
-- ERAM DEZ, VIRARAM NOVE NO PR-J8 (ADR s3-24): saíram FK_CKRES_PRESCRICAO e
-- FK_CKRES_REGRA junto com T_PB_CHECKIN_RESULTADO, e entrou
-- FK_ITEM_REGRA_APLICADA, porque ID_REGRA_APLICADA passou para dentro do item.
--
-- Note a assimetria de precisão: a coluna de origem é NUMBER(19) (Long do Java)
-- e a de destino é NUMBER(10) (int do .NET). É deliberado — cada lado declara o
-- que o próprio ORM gera.
--
-- FONTE: database/src/01_ddl.sql, commit a73a473.
-- =============================================================================

ALTER TABLE T_PB_USUARIO ADD CONSTRAINT FK_USUARIO_VETERINARIO
    FOREIGN KEY (ID_VETERINARIO) REFERENCES T_PB_VETERINARIO (ID_VETERINARIO);
ALTER TABLE T_PB_USUARIO ADD CONSTRAINT FK_USUARIO_RESPONSAVEL
    FOREIGN KEY (ID_RESPONSAVEL) REFERENCES T_PB_RESPONSAVEL (ID_RESPONSAVEL);

ALTER TABLE T_PB_PLANO_CUIDADO ADD CONSTRAINT FK_PLANO_ANIMAL
    FOREIGN KEY (ID_ANIMAL) REFERENCES T_PB_ANIMAL (ID_ANIMAL);
ALTER TABLE T_PB_PLANO_CUIDADO ADD CONSTRAINT FK_PLANO_CONSULTA
    FOREIGN KEY (ID_CONSULTA) REFERENCES T_PB_CONSULTA (ID_CONSULTA);

ALTER TABLE T_PB_ITEM_PLANO_CUIDADO ADD CONSTRAINT FK_ITEM_PRESCRICAO
    FOREIGN KEY (ID_PRESCRICAO) REFERENCES T_PB_PRESCRICAO (ID_PRESCRICAO);
ALTER TABLE T_PB_ITEM_PLANO_CUIDADO ADD CONSTRAINT FK_ITEM_PROCEDIMENTO
    FOREIGN KEY (ID_PROCEDIMENTO) REFERENCES T_PB_PROCEDIMENTO (ID_PROCEDIMENTO);
-- A nona, trazida pela fusão do ADR s3-24: a regra que decidiu a dose é do
-- registro, e o item que a cita é do cuidado.
ALTER TABLE T_PB_ITEM_PLANO_CUIDADO ADD CONSTRAINT FK_ITEM_REGRA_APLICADA
    FOREIGN KEY (ID_REGRA_APLICADA) REFERENCES T_PB_REGRA_PRESCRICAO (ID_REGRA_PRESCRICAO);

-- as quatro que o cluster do check-in acrescentou ao mudar de lado (08/09)
ALTER TABLE T_PB_CHECKIN ADD CONSTRAINT FK_CHECKIN_ANIMAL
    FOREIGN KEY (ID_ANIMAL) REFERENCES T_PB_ANIMAL (ID_ANIMAL);
ALTER TABLE T_PB_CONDICAO_OBSERVADA ADD CONSTRAINT FK_COBS_CONDICAO
    FOREIGN KEY (ID_CONDICAO_CLINICA) REFERENCES T_PB_CONDICAO_CLINICA (ID_CONDICAO_CLINICA);
